# Site settings
title: Daily Magic Spells 
subtitle: by Areteem Institute of Witchcraft and Wizardry

baseurl: /Math123 # the subpath of your site, e.g. /blog/
highlighter: rouge

url: "http://leiw2000.github.io/"
github_username: Leiw2000
description: These are problems by Areteem Institute of Witchcraft and Wizardry
# Build settings
markdown: kramdown

collections:
  questions:
    output: true

