# Site settings
title: Daily Magic Spells by Areteem Institute of Witchcraft and Wizardry
# email: ev3commander@outlook.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mathmaven.github.io" 

github_username: MathMaven

# Build settings
markdown: kramdown
