# Site settings
title: Daily Magic Spells 
subtitle: by Areteem Institute of Witchcraft and Wizardry
# email: ev3commander@outlook.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mathmaven.github.io" 

github_username: MathMaven
description: These are problems by Areteem Institute of Witchcraft and Wizardry
# Build settings
markdown: kramdown
