# Site settings
title: Daily Math Questions
email: ev3commander@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the daily questions from Dr. Wang, Feng, Areteem.
baseurl: "/MathMaven/" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

github_username:  ev3commander

# Build settings
markdown: kramdown
