# Site settings
title: Daily Math Challenges by Dr. Kevin Wang
# email: ev3commander@outlook.com
description: These are the daily questions from Dr. Kevin Wang, "url:http://www.areteem.org" Areteem Institute. &copy; Copyright 2015
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mathmaven.github.io" # the base hostname & protocol for your site

github_username: MathMaven

# Build settings
markdown: kramdown
