# Site settings
title: Daily Magic Spells 
subtitle: by Areteem Institute of Witchcraft and Wizardry
# email: ev3commander@outlook.com
baseurl: \Math123 # the subpath of your site, e.g. /blog/

github_username: Leiw2000
description: These are problems by Areteem Institute of Witchcraft and Wizardry
# Build settings
markdown: kramdown
